okta/okta-oidc-ios

- Example/Okta.xcodeproj/project.pbxproj
- Example/Okta/Okta-PasswordFlow.plist
- Example/Tests/Tests.swift
- Okta/OktaAuth.swift
- Okta/OktaLogin.swift
- During the resource owner password flow, if the invalid credentials are included - we currently return a force-unwrapped "error". This error should be the local error, not the parent error.
Resolves: OKTA-144867
> :bug: Fixes force unwrapping error

- Example/Tests/Tests.swift
- Okta/OktaIntrospection.swift
- Okta/OktaRevoke.swift
- Okta/OktaUserInfo.swift
When **not** using the `well-known` discovery metadata, we were expecting URLs to be in the format: `https://org.com/oauth2/authServerId`.
This **fix** is to detect when using a custom AS or default AS.
> :bug: Fixed issue where URLs were malformed

- Example/Okta/Okta-PasswordFlow.plist
- Example/Okta/Okta.plist
- Example/Tests/Tests.swift
- Okta/OktaAuth.swift
- Okta/OktaError.swift
- Okta/OktaLogin.swift
- Okta/OktaUtils.swift
- README.md
BREAKING CHANGE
- Removes scope instantiation by validating scopes are in `String` format instead of checking for `String` Array.
> :fire: Updates scope value

- Example/Tests/Tests.swift
- Okta/OktaApi.swift
- Okta/OktaAuth.swift
- Okta/OktaIntrospection.swift
- Okta/OktaLogin.swift
- Okta/OktaRevoke.swift
- Okta/OktaUtils.swift
- 🌱 Extends the ability to pass in optional parameters to the `/authorization` endpoint
- 🌱 Allows login to be kicked off using a `[String: String]` object instead of `.plist`
Resolves: #32
> :seedling: Adds ability to pass additionalParams to the /authorize

- Example/Okta/Base.lproj/Main.storyboard
- Example/Okta/ViewController.swift
- Example/Okta_UITests/Okta_UITests.swift
- Okta/OktaAppAuth.swift
- Okta/OktaError.swift
- Okta/OktaRefresh.swift
- Updates the `OktaAuth.refresh` method to extend `getFreshTokens()` and be `private`. Tokens will be refreshed automatically (in a follow-up PR).
Primarily, this change is to explicitly wait or throw if a token can/cannot be refreshed. By returning a promise, it is easy to handle the event where  new tokens are received.
> Updates refresh to return a promise

- Example/Tests/Tests.swift
- Okta/OktaAppAuth.swift
- Okta/OktaAuth.swift
- Okta/OktaError.swift
- Okta/OktaIntrospection.swift
- Okta/OktaRevoke.swift
- Okta/OktaUserInfo.swift
- Caches the well-known endpoint response data for easy retrieval
- Adds tests to validate `accessToken` is provided to certain methods
> :seedling: Cache well-known for easy access

- .travis.yml
- Example/Okta.xcodeproj/project.pbxproj
- Example/Okta.xcodeproj/xcshareddata/xcschemes/Okta-Example.xcscheme
- Example/Okta/Okta.plist
- Example/Okta/ViewController.swift
- Example/Okta_UITests/Okta_UITests.swift
- Example/Okta_UITests/UITestUtils.swift
- Example/Tests/TestUtils.swift
- Example/Tests/Tests.swift
- Okta/OktaAppAuth.swift
- Okta/OktaAuth.swift
- Okta/OktaRefresh.swift
- Okta/OktaTokenManager.swift
- Okta/OktaUserInfo.swift
- README.md
- scripts/build-and-test.sh
- scripts/helpers.sh
Allows the ability to easily manage user state on app setup. The method `isAuthenticated()` checks for an `accessToken` stored in the Keychain. If available, it will attempt to deserialize the last `authState` response to resume the user's state.
```swift
// ViewController.swift
override func viewDidLoad() {
...
if !OktaAuth.isAuthenticated() {
// Start the login flow
}
}
```
Resolves: [OKTA-153412](https://oktainc.atlassian.net/browse/OKTA-153412) and #21
> Adds helper method for determining + resuming the authState

- Example/Okta.xcodeproj/project.pbxproj
- Example/Podfile
- Example/Tests/TestUtils.swift
- Example/Tests/Tests.swift
- Okta/OktaAuth.swift
- Okta/OktaError.swift
- Okta/OktaIntrospection.swift
- Okta/OktaTokenManager.swift
- Okta/OktaUtils.swift
- OktaAuth.podspec
🌱 Before the token is placed into storage, the `idToken` is validated per [OIDC 3.1.3.7](http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation)
- Our implementation *does* make opinionated validation assumptions (clock-drift, nonce, etc)
- For testing purposes, we allow validation options to be passed into the `TokenManager` constructor. This will be bubbled up to the developer in a follow-up PR.
Resolves: OKTA-157796
> :seedling: Adds idToken validation

- Example/Okta/Okta-PasswordFlow.plist
- Example/Tests/TestUtils.swift
- Example/Tests/Tests.swift
- Okta/OktaAuth.swift
- Okta/OktaIntrospection.swift
- Okta/OktaRefresh.swift
- Okta/OktaRevoke.swift
When using the ROPF - tokens would not be refreshed due to the `lastAuthorizationResponse` always returning `nil`.
Tokens are now manually refreshed if there is no `lastAuthorizationResponse` attached to the current `authState` and a `refreshToken` is available.
> :bug: Fix tokens not being refreshed when using ROPF

- Example/Tests/TestUtils.swift
- Example/Tests/Tests.swift
- Okta/OktaAppAuth.swift
- Okta/OktaTokenManager.swift
- README.md
- Before tokens are returned via the TokenManger, they are checked against their expiration time.
- Expose `Refresh` abilities for tokens
> :seedling: Check for expiration on tokens before return

- Example/Tests/TestUtils.swift
- Example/Tests/Tests.swift
- Okta/OktaError.swift
- Okta/OktaRefresh.swift
- Okta/OktaTokenManager.swift
On successful authentication, the user's auth context is serialized so it can be resumed in the future. Upon an application's resumed state, an attempt to deserialize the stored data is made, including re-initializing the `TokenManager` object. Oftentimes tokens are expired when attempting to resume state, which caused the constructor to fail and throw an exception.
This PR contains a fix for the above issue, removing token validation when initializing the `TokenManager`, **only** validating the token on attempted used.
- #64 
- [OKTA-184308](https://oktainc.atlassian.net/browse/OKTA-184308)
> :bug: Fixes issue where tokenManager instance was not being created

- Okta/OktaAuth/OktaApi.swift
- Okta/OktaAuth/OktaAuth.swift
- Okta/OktaAuth/OktaIntrospection.swift
- Okta/OktaAuth/OktaRevoke.swift
- Okta/OktaAuth/OktaUserInfo.swift
First step in removing HydraAsync dependency is to rework class responsible for network requests to Okta API. This will facilitate separation of further work into several patches.
Reworked OktaAPI class to omit using Hydra async.
Revoke, Introspect, GetUserInfo, SignIn, SignOut functionality.
UI tests
> OKTA-211992 Remove HydraAsync from public API

- Example/Okta/ViewController.swift
- Example/Tests/OktaAuthTokenManagerTests.swift
- Okta/OktaAuth/OktaAuthStateManager.swift
- README.md
In OktaAppAuth SDK 3.0 we will add support for multiple Oauth 2.0 accounts. So developer can use Okta endpoint, social endpoint and others in one application. There is one part in the solution that doesn't look great - using of hardcoded key for storing OktaAuthStateManager instance. This leads to the following issue:
1. OktaAuthStateManager instance for Okta endpoint is saved with hardcoded key - "OktaAuthStateTokenManager"
2. OktaAuthStateManager instance for social endpoint is saved with hardcoded key - "OktaAuthStateTokenManager"
Actual outcome:
OktaAuthStateManager instance for social endpoint overwrites Okta's data in keychain
To cope with that we have to add additional function for storing/retrieving data from keychain. Function should accept custom key for saving. Since …
> OKTA-218175 AppAuth iOS: Save AuthState object to keychain with composite key

- Example/Okta/AppDelegate.swift
- Example/Okta/AuthViewController.swift
- Example/Okta/ViewController.swift
- Example/Okta_UITests/Okta_UITests.swift
- Example/Tests/OktaOidcConfigTests.swift
- Example/Tests/OktaOidcDiscoveryTaskTests.swift
- Example/Tests/OktaOidcEndpointTests.swift
- Example/Tests/OktaOidcKeychainTests.swift
- Example/Tests/OktaOidcStateManagerTests.swift
- Example/Tests/OktaOidcTests.swift
- Example/Tests/OktaOidcUtilsTests.swift
- Example/Tests/TestUtils.swift
- Okta/OktaOidc/OktaOidcStateManager.swift
OKTA-221606 - OIDC iOS: Keychain read with long keys fails
https://oktainc.atlassian.net/browse/OKTA-221606
- Change key generation logic according to the design
- Tests
- OktaOidcStateManager
Added
> OKTA-221606-OIDC iOS: Keychain read with long keys fails

- Okta/OktaOidc/OktaOidc.swift
- OktaOidc.podspec
- README.md
Delta:
OKTA-221606-OIDC iOS: Keychain read with long keys fails - [`4a5b5ce`](https://github.com/okta/okta-oidc-ios/commit/4a5b5ce2ca351303357fcdf533b334a669df4665)
Addresses:
https://github.com/okta/okta-oidc-ios/issues/137
> Release increment - 3.1.0

- Okta/AppAuth/OIDExternalUserAgentIOS.m
`UIApplication.sharedApplication.keyWindow` is deprecated
https://developer.apple.com/documentation/uikit/uiapplication/1622924-keywindow?language=objc
> OKTA-244292-iOS OIDC SDK: UIApplication.keyWindow is deprecated in iOS13

- .travis.yml
- Example/AppDelegate.swift
- Okta/AppAuth/iOS/OIDExternalUserAgentNoSsoIOS.h
- Okta/AppAuth/iOS/OIDExternalUserAgentNoSsoIOS.m
- Okta/Framework/Info.plist
- Okta/OktaOidc/Internal/OktaUserAgent.m
- Okta/OktaOidc/Internal/Tasks/iOS/OktaOidcBrowserTaskIOS.swift
- Okta/OktaOidc/OktaOidc.h
- Okta/OktaOidc/OktaOidcConfig.swift
- Okta/OktaOidc/OktaOidcKeychain.swift
- Okta/OktaOidc/iOS/OktaOidc+Browser.swift
- OktaOidc.podspec
- README.md
- Tests/OIDExternalUserAgentNoSsoTests.swift
- Tests/OktaOidcConfigTests.swift
- UITests/UITestUtils.swift
- okta-oidc.xcodeproj/project.pbxproj
- okta-oidc.xcodeproj/xcshareddata/xcschemes/okta-oidc.xcscheme
Need a way to implicitly enable `prefersEphemeralWebBrowserSession`  for `ASWebAuthenticationSession` class.
- Add `noSSO` flag into `OktaOidcConfig` class
- Create `OIDExternalUserAgentNoSsoIOS` class that conforms to `OIDExternalUserAgent`
- Create instance of `OIDExternalUserAgentNoSsoIOS` if `noSSO` flag is true
OktaOidcConfig, OktaOidcBrowserTaskIOS
Added
> OKTA-309958 - [OIDC SDK] option to set prefersEphemeralWebBrowserSession

- Okta/OktaOidc/Internal/OIDAuthState+Okta.swift
- Tests/OIDAuthStateTests.swift
- Tests/OktaOIDAuthStateTests.swift
- okta-oidc.xcodeproj/project.pbxproj
In OIDAuthState+Okta.swift, we didn't pass the delegate to the bottom network layer.
Pass the delegate to the bottom network layer
OIDAuthState+Okta.swift
Actual result:
> Pass delegate in get auth state method

- Package.swift
The library did not support Swift Package Manager (SPM).
Added a file, `Package.swift`, that allows integration with SPM.
> Add Support for Swift Package Manager

- README.md
- Sources/OktaOidc/Common/OktaOidc.swift
- Sources/OktaOidc/Common/OktaOidcConfig.swift
- Sources/OktaOidc/Common/OktaOidcStateManager.swift
- Sources/OktaOidc/iOS/OktaOidc+BrowserIOS.swift
- Sources/OktaOidc/macOS/OktaOidc+BrowserMAC.swift
- Tests/OktaOidcTests/OktaOidcBrowserTests.swift
- Tests/OktaOidcTests/OktaOidcConfigTests.swift
When signing in, additional parameters may be required without rebuilding the Okta config from scratch.
Add an additional optional argument to supply a dictionary of values to signInWithBrowser, and merge that into a new configuration that is supplied to the login task.
Actual result:
> Allow IDP parameters to be supplied when invoking signInWithBrowser

- Swift code guidelines.md
**DISCLAIMER:** This PR is not going to being merged into `master`. It is created for convenient review by iOS developers.
Described rules are not set in stone - new items can be added, existing ones - removed. 
Discussion and communication are very welcome.
[OKTA-366025](https://oktainc.atlassian.net/browse/OKTA-366025)
- [1. Code formatting](#code-formatting)
- [2. Naming](#naming)
- [3. Coding Style](#coding-style)
- [4. Don'ts](#don'ts)
1.1 Use 4 spaces to indent lines.
1.2. Trim trailing whitespaces (`Xcode` -> `Preferences` -> `Text Editing` -> `Automatically trim trailing whitespace` + `Including whitespace-only lines`).
1.3. No space before colon and one space after it. Exceptions are the ternary operator `? :`, empty dictionary `[:]` and `#selector` syntax `addTarget(_:action:)`. …
> Add Swift code style-guide for review by iOS devs

- Sources/OktaOidc/Common/Internal/OIDAuthState+Okta.swift
- Sources/OktaOidc/Common/OktaOidc.swift
- Sources/OktaOidc/Common/OktaOidcStateManager.swift
- Tests/Common/URLSessionMock.swift
- Tests/OktaOidcTests/OktaOIDAuthStateTests.swift
- Tests/OktaOidcTests/OktaOidcStateManagerTests.swift
In issues #287, there are circumstances where the OktaNetworkRequestCustomizationDelegate may become unset, or impossible to re-set, which prevents developers from monitoring or overriding the network request process.
Two primary changes were introduced:
1. Supply the delegate to the OKTAuthState initializer when it is created using `OKTAuthState.getState`
2. Expose a `delegate` property on the OktaOidcStateManager that permits setting the REST API delegate property, without exposing the full OktaOidcRestApi object.
OKTAuthState and OktaOidcStateManager.
1. Perform `OKTAuthState.getState` with a delegate.
2. Examine the resulting state object.
Actual result:
The delegate value is dropped on the new object.
The delegate should persist in the newly created object.
Added …
> Ensure the network request customization delegate is maintained or resettable when relaunching the application

- Sources/AppAuth/iOS/OKTExternalUserAgentIOS.m
- Sources/AppAuth/iOS/OKTExternalUserAgentIOSCustomBrowser.m
The okta-oidc library uses the openURL: API, which has been deprecated since iOS 10.0. The library should be updated to utilize the new API.
`open(_:options:completionHandler:)` called now.
> Updated method openURL

- Sources/OktaOidc/Common/OktaOidcStateManager.swift
Data read/write by OktaOidc is not compatible between versions , iOS SDK version 3.9.1  to 3.10.4. The problem is in renamed files in https://github.com/okta/okta-oidc-ios/pull/249/files. 
Fixed by using `NSKeyedUnarchiver.setClass(:forClassName:)`. 
`OktaOidcStateManager.swift`
No unit tests written because of issue trickiness. Manual testing verifies this fix.
> Data read write by okta OIDC is not compatible between versions

- Example/AuthViewController.swift
- Example/ViewController.swift
- README.md
- Sources/OktaOidc/Common/Internal/OIDAuthState+Okta.swift
- Sources/OktaOidc/Common/Internal/OIDAuthorizationService+Okta.swift
- Sources/OktaOidc/Common/Internal/OktaOidcRestApi.swift
- Sources/OktaOidc/Common/Internal/Tasks/OktaOidcBrowserTask.swift
- Sources/OktaOidc/Common/Internal/Tasks/OktaOidcTask.swift
- Sources/OktaOidc/Common/OktaOidcError.swift
- Tests/OktaOidcTests/OktaOidcDiscoveryTaskTests.swift
- Tests/OktaOidcTests/OktaOidcEndpointTests.swift
- Tests/OktaOidcTests/OktaOidcErrorTests.swift
- Tests/OktaOidcTests/OktaOidcStateManagerTests.swift
- okta-oidc.xcodeproj/project.pbxproj
The error handling is not convenient in our SDK. It throws general `APIError` but doesn't provide additional error info where it may be helpful for better app UX.
Minimal changes to keep backward-compatibility and minimal customer' code changes. In general, error handling in the SDK must be refreshed. 
Refactoring `APIError` and improved somewhere error messages. 
`OktaOidcError`
[OKTA-448284](https://oktainc.atlassian.net/browse/OKTA-448284)
Will be added soon.
> Generic error code is returned for all authorization

- Sources/AppAuth/macOS/OKTRedirectHTTPHandler.m
Chrome has a preflight check for local network requests that requires our loopback listener to respond in a specific way in order to receive the proper GET request.
Chrome document: https://developer.chrome.com/blog/private-network-access-preflight/
This document also says we need to include the
`Access-Control-Allow-Origin` header as well in order to succeed, but in my (admittedly limited) tests that wasn't necessary. If it's deemed prudent, I can add that to this PR as well.
> Handle private network preflight call

- Sources/AppAuth/macOS/OKTRedirectHTTPHandler.m
During initial testing, the original fix was working, but in subsequent testing, these additional headers were required to allow Chrome to redirect to the loopback server successfully.
> Update private network preflight

- .github/workflows/okta-oidc.yml
- OktaOidc.podspec
- Sources/AppAuth/OktaUserAgent.m
- Sources/AppAuth/macOS/OKTRedirectHTTPHandler.m
- Tests/AppAuthTests/OKTRedirectHTTPHandlerTests.m
- okta-oidc.xcodeproj/project.pbxproj
Check results of `CFHTTPMessageCopyRequestMethod` and `CFHTTPMessageCopyRequestURL` for nil
> OKTA-748810 - Crash/Non-fatal - <CF_IS_OBJC Firebase>
