.travis.yml, OktaAuth.podspec, scripts/build-and-test.sh
=> Updating App Auth SDK for iOS 11 support

OktaAuth.podspec
⬆️ Updates version to `0.2.0` to support iOS 11
=> Release 0.2.0

Example/Okta.xcodeproj/project.pbxproj, Example/Okta/Okta.plist, Example/Okta_UITests/Okta_UITests.swift, Example/Tests/Tests.swift, Okta/OktaApi.swift, Okta/OktaAppAuth.swift, Okta/OktaAuth.swift, Okta/OktaIntrospection.swift, Okta/OktaLogin.swift, Okta/OktaRevoke.swift, Okta/OktaUserInfo.swift, Okta/OktaUtils.swift
- :bug: Various small bug fixes
- 🌱 Adds `X-Okta-User-Agent-Extended` header
- ⬆️ Increment hard coded version for API calls
=> :bug: Fixes trailing slash breaking API calls + adds user agent header

Example/Okta/Okta.plist, Example/Tests/Tests.swift, Okta/OktaApi.swift, Okta/OktaAppAuth.swift, Okta/OktaAuth.swift, Okta/OktaError.swift, Okta/OktaIntrospection.swift, Okta/OktaKeychain.swift, Okta/OktaLogin.swift, Okta/OktaRevoke.swift, Okta/OktaTokenManager.swift, Okta/OktaUserInfo.swift, Okta/OktaUtils.swift, README.md
- Update error messages to be caught by name
- Remove extra newlines and whitespace
=> Improve error messages + minor fixes

Example/Okta.xcodeproj/project.pbxproj, Example/Okta/Okta.plist, Okta/OktaApi.swift, Okta/OktaAppAuth.swift, Okta/OktaAuth.swift, Okta/OktaUtils.swift
All `HTTP` requests are passed a custom header named: `X-Okta-User-Agent-Extended`
=> Updates custom user-agent header

Example/Tests/Tests.swift, Okta/OktaAuth.swift, Okta/OktaIntrospection.swift, Okta/OktaLogin.swift, Okta/OktaRevoke.swift, Okta/OktaUserInfo.swift, Okta/OktaUtils.swift
- Updates `Util` class to use class methods
- Remove whitespace
- Removes trailing slash `/` to build API requests properly
=> :bug: Fixes trailing slash on API calls

Okta/OktaApi.swift, Okta/OktaAppAuth.swift, Okta/OktaAuth.swift, Okta/OktaIntrospection.swift, Okta/OktaKeychain.swift, Okta/OktaLogin.swift, Okta/OktaTokenManager.swift, OktaAuth.podspec
- Cleanup existing newlines + tabs
=> :memo: Cleanup whitespace

Example/Tests/Tests.swift, Okta/OktaApi.swift, Okta/OktaAuth.swift, Okta/OktaError.swift, Okta/OktaIntrospection.swift, Okta/OktaLogin.swift, Okta/OktaRevoke.swift, Okta/OktaUserInfo.swift
BREAKING CHANGE
- Updates error messages to be easily distinguishable
=> :memo: Updates error messages

Example/Okta.xcodeproj/project.pbxproj, Example/Okta/Images.xcassets/AppIcon.appiconset/Contents.json, Example/Okta/Okta-PasswordFlow.plist, Example/Okta_UITests/Okta_UITests.swift, Example/Okta_UITests/UITestUtils.swift
=> :bug: Fix UI tests

OktaAuth.podspec
=> Release 0.3.0

Example/Okta.xcodeproj/project.pbxproj, Example/Okta/ViewController.swift, Example/Tests/Tests.swift, Okta/OktaApi.swift, Okta/OktaAuth.swift, Okta/OktaError.swift, Okta/OktaIntrospection.swift, Okta/OktaLogin.swift, Okta/OktaRevoke.swift, Okta/OktaUserInfo.swift, OktaAuth.podspec
- Update closures to be [promises](https://github.com/malcommac/Hydra) to increase code readability
=> :arrow_up: Update closures to be promises

Example/Okta/Base.lproj/Main.storyboard, Example/Okta/ViewController.swift, Example/Okta_UITests/Okta_UITests.swift, Example/Tests/Tests.swift, Okta/OktaAppAuth.swift, Okta/OktaError.swift, Okta/OktaIntrospection.swift
BREAKING CHANGE
- Renames `OktaAuth.userinfo` to `OktaAuth.getUser`
- Adds helper method for decoding a `jwt`
=> :seedling: Adds getUser helper method

Example/Okta/ViewController.swift, Example/Tests/Tests.swift, Okta/OktaApi.swift, Okta/OktaAuth.swift, Okta/OktaIntrospection.swift, Okta/OktaLogin.swift, Okta/OktaRevoke.swift, Okta/OktaUserInfo.swift, Okta/OktaUtils.swift
- Adds `Promise` return type to `login` functions
- Use `guard` instead of `if let` in various places
- Pull out shared code
=> Code cleanup

Example/Okta/LoginFormViewController.swift
Bringing in the changes from #59 to run Travis tests
- Changed "Okta-PasswordFlowz" to "Okta-PasswordFlow"
=> :bug: Fix typo

OktaAuth.podspec
- [`5b01ada`](https://github.com/okta/okta-sdk-appauth-ios/commit/5b01adac8145e745701e81b235908338fff38db8) - Fixes an issue where the tokenManager instance was not being created and tokens were not stored after a refresh.
=> Release 1.0.1

Example/Okta.xcodeproj/project.pbxproj, Example/Okta.xcodeproj/xcshareddata/xcschemes/Okta-Example.xcscheme, Example/Okta/Base.lproj/Main.storyboard, Example/Okta/Info.plist, Example/Okta/Okta.plist, Example/Okta/ViewController.swift, Example/Okta_UITests/Okta_UITests.swift, Example/Podfile, Example/Tests/TestUtils.swift, Example/Tests/Tests.swift, Okta/OktaAppAuth.swift, Okta/OktaAuth.swift, Okta/OktaError.swift, Okta/OktaExternalUserAgentIOS.swift, Okta/OktaLogout.swift, Okta/OktaRevoke.swift, Okta/OktaTokenManager.swift, OktaAuth.podspec, README.md, scripts/build-and-test.sh
Carried over commits from #87:
- AppAuth dev-logout branch integration
- logout API implementation
- updated Example with logout flow
- added logout description in READMY
- switched to use OktaAppAuth
- added UI tests for Sign Out
- #7
=> Logout Flow merge to master

Okta/OktaAppAuth.swift, README.md
Updates the README with changes introduced with `2.0.0` and adds previously undocumented methods.
- #97
=> Updates README with new API changes

OktaAuth.podspec
=> Switched to latest OktaAppAuth release

Okta/OktaAuth.swift, Okta/OktaError.swift, Okta/OktaSignIn.swift, Okta/OktaSignOut.swift
=> Improved plist parsing errors

Example/Okta/ViewController.swift, Example/Okta_UITests/Okta_UITests.swift, Okta/OktaAuth.swift
I've found out that auth state storage was broken after logout change.
Fixed that.
=> Restored missing storage of auth state after login.

Okta/OktaAppAuth.swift, OktaAuth.podspec
Prepare podspec file for new release
=> Podspec major version increment

Example/Tests/AppAuthTests/OIDTokenRequestTests.m, Okta/AppAuth/OIDTokenRequest.m, Okta/OktaAuth/OktaApi.swift, Okta/OktaAuth/OktaUtils.swift
=> Ensure User-Agent is sent

Example/Okta/Okta.plist
=> Consistent placeholders and labels

Okta/OktaOidc/OktaOidcUtils.swift
Fix http user agent with correct library name
=> Fix user agent

README.md
https://github.com/okta/okta-oidc-ios/issues/159
=> Broken anchor link in readme #159

Example/Base.lproj/Main.storyboard, UITests/Okta_UITests.swift
XCUITest engine raises exception when sees multiple buttons with the same name in UI hierarchy
Redo test implementation
=> Fix test that is failing on iOS 13 beta

Example/ViewController.swift, Okta/OktaOidc/OktaOidc.swift, Okta/OktaOidc/OktaOidcKeychain.swift, Okta/OktaOidc/OktaOidcStateManager.swift, Okta/OktaOidc/OktaSignOutOptions.swift, Okta/OktaOidc/OktaUserAgent.m, OktaOidc.podspec, README.md, okta-oidc.xcodeproj/project.pbxproj, okta-oidc/Resources/Info.plist
Implement new signOut flow that includes multiple steps: revoke tokens, deletion of persistent cookie, persistence storage clean-up
- Define new class `OktaSignOutOptions`
- Define new function: signOut(with options:)
Will be added in separate PR
=> OKTA-247564 - Design helper api for OIDC iOS sdk

Okta/Framework/Info.plist, Okta/OktaOidc/Internal/OktaUserAgent.h, Okta/OktaOidc/Internal/OktaUserAgent.m, Okta/OktaOidc/OktaOidcConfig.swift, OktaOidc.podspec, Tests/OktaOidcConfigTests.swift
- Add function to provide custom user agent
- Unit test
- Release increment
=> Customize user agent

UITests/UITestUtils.swift, okta-oidc.xcodeproj/xcshareddata/xcschemes/okta-oidc.xcscheme
- Fix e2e tests
- Enable e2e tests target
=> OKTA-312467 - OIDC: Fix UI tests for both OIDC sdk and samples app repos

OktaOidc.podspec, Sources/AppAuth/OktaUserAgent.m, okta-oidc.xcodeproj/project.pbxproj
=> Release increment to 3.9.3

OktaOidc.podspec, Sources/AppAuth/OktaUserAgent.m, okta-oidc.xcodeproj/project.pbxproj
Incremented release version number to include signin support with IDP parameters.
Actual result:
=> Incremented release version to 3.10.0

Sources/OktaOidc/Common/Internal/Tasks/OktaOidcBrowserTask.swift, Sources/OktaOidc/Common/OktaOidcError.swift
=> Adding error case for when oidc flow is cancelled by user

OktaOidc.podspec, Sources/AppAuth/OktaUserAgent.m, okta-oidc.xcodeproj/project.pbxproj
=> Incrementing release version to 3.10.1

OktaOidc.podspec, Sources/AppAuth/OktaUserAgent.m, okta-oidc.xcodeproj/project.pbxproj
Increment version number to 3.10.3
=> Increment version number to 3.10.3

Example/ViewController.swift, Sources/AppAuth/OKTAuthState.m, Sources/AppAuth/include/OKTAuthState.h, Sources/OktaOidc/Common/OktaOidcStateManager.swift, Tests/OktaOidcTests/OktaOIDAuthStateTests.swift, Tests/OktaOidcTests/OktaOidcStateManagerTests.swift
Fixes [OKTA-393719](https://oktainc.atlassian.net/browse/OKTA-393719).
=> OKTA-393719 > Make delegate public in OKTAuthState

OktaOidc.podspec, Sources/AppAuth/OktaUserAgent.m, okta-oidc.xcodeproj/project.pbxproj
Increment version number to 3.10.4
=> Increment version number to 3.10.4

LICENSE, OktaOidc.podspec, okta-oidc.xcodeproj/project.pbxproj
=> Increment version to 3.10.5

OktaOidc.podspec, Sources/AppAuth/OktaUserAgent.m, okta-oidc.xcodeproj/project.pbxproj
=> Increment version to 3.10.6

OktaOidc.podspec, Sources/AppAuth/OktaUserAgent.m, okta-oidc.xcodeproj/project.pbxproj
=> Increment version to 3.10.7

OktaOidc.podspec, Sources/AppAuth/OktaUserAgent.m, okta-oidc.xcodeproj/project.pbxproj
=> Version increment to 3.10.8
